[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
     \.git          # root of the project
    | data 
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pylint.messages_control]
disable = "C0330, C0326, C0103, E0602, W0511"

[tool.pylint.format]
max-line-length = "120"

[tool.interrogate]
verbose = 2
